### ISSUE TITLE
Apply Gainmap

### ISSUE THREAD

**Issue by hiepthb2020** [amirzaidi/DNGProcessor#3]
Hi @amirzaidi,
how to apply lenshadingmap with opengl version?

**Comment by amirzaidi** [comment]
The lens shading map is not saved in many devices' DNG files so there's currently no support for parsing it

**Comment by hiepthb2020** [comment]
I guess currently this project missing lens correction step so the result seem to be brighter in the center and darkened out.

**Comment by hiepthb2020** [comment]
If have lens shading map, how to convert gainmap function from RS version to OpenGL version? @amirzaidi .

Thanks,

**Comment by hiepthb2020** [comment]
Hi @amirzaidi,
i was make a comparison between 2 version of DNGProcessor and apply in https://github.com/googlesamples/android-Camera2Raw to process DNG to JPEG:

[RS version](https://imgur.com/smHSHfP)
[OpenGL version](https://imgur.com/8lEJ5iB)
[JPEG output from device](https://imgur.com/AsXLT54)

In RS version, I applied lens shading map and the result is more better.

**Comment by amirzaidi** [comment]
I know that it is better, the problem is that the gainmap is not included in the output DNG file for the phones where I'm testing on, and is only available as metadata from the Camera2 API. I'd have to make a database of gainmaps for different lenses before I could implement it using these DNG files

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/DNGProcessor/commit/b26469a1888c54c4d8ef4585bc4d53ab04902802

Implemented it, but it won't work on many OEM Camera apps

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/DNGProcessor/commit/6901fcbf61c401904ecc70977d26dc3a8fefa52e#diff-517914f0c5a571d32c52c15f1aea9aebL37

This change fixed the coordinate sampling, so now it actually works...
